### ISSUE TITLE
NameError: uninitialized constant Category::Category

### ISSUE THREAD

**Issue by rutgerg** [collectiveidea/awesome_nested_set#169]
Hello,

love the gem. Txs. Everything works except for 1 thing. Whenever I try to use the move_to_child_of method exactly as in the cheat sheet I get an error saying NameError: uninitialized constant Category::Category. What is going wrong here?

Regards,

Rutger

**Comment by kinsomicrote** [comment]
Has this issue been fixed, cause I am having same problem in my app.

**Comment by rutgerg** [comment]
This is such a long time ago that I can't remember what I did to solve it at that time. I don't use the gem anymore. Sorry.
