### ISSUE TITLE
Nested sets of different classes? (i.e. 'File' class inside 'Folder' class)

### ISSUE THREAD

**Issue by thoughtpunch** [collectiveidea/awesome_nested_set#203]
I'd like to user `awesome_nested_set` to implement a simple directory tree structure in my data model ( "files" inside folders of arbitray depth)

I implemented simple _File_ and _Folder_ classes which nest inside other instances of the same class just fine. However, when I try to add a File as a child of a Folder, the `move_to_child_of` method does a lookup by ID in the table of the child ( "files" in this example).

Is there any way to accomplish the nesting of files inside folders?

**Comment by bricesanchez** [comment]
@thoughtpunch Did you find a solution for this missing feature ?

**Comment by thoughtpunch** [comment]
@bricesanchez I ended up using a 1-level deep psuedo File/Folder structure (i.e. "folder_id" on the File model) although it shouldn't be too hard to implement the above with polymorphic relationships like `lft_id` , `lft_type`, `rgt_id`, `rgt_type` etc
