### ISSUE TITLE
Single Table Inheritance in 3.0.0.rc.1

### ISSUE THREAD

**Issue by axlekb** [collectiveidea/awesome_nested_set#209]
I recently switched over to awesome_nested_set after realizing that closure_tree hit the db on initialization which is a pain in the butt if you're using Heroku.

I tried out 2.1.6 and my tests passed, but with a lot of deprecation warnings.  I tried out 3.0.0.rc.1, but ran into some problems in my spec with what I think comes down to single table inheritance.

I have this structure:
Superclass (i.e. Fruit):
--SubClass1 (i.e. Berry)
--SubClass2 (i.e. Blueberry)

To reproduce:
1. Create instance of Berry.
2. Create instance of Blueberry with the id of Berry as the parent_id.

Immediately after creating the Blueberry, the first awesome_nested_set callback that hits the database looks for a Blueberry matching the parent_id rather than just a Fruit with that parent_id. It also looks like default scopes are now built in.  

I didn't see anything in the changelog about this, but just wanted to ask if this was expected behavior.  

Here are the db queries:

2.1.6 (works)

```
  Fruit Load (0.6ms)  
SELECT "fruits".* 
FROM "fruits" 
WHERE "fruits"."id" = $1 
ORDER BY "fruits"."lft" LIMIT 1  [["id", 1]]
```

3.0.0.rc.1 (causes RecordNotFound)

```
  Blueberry Load (0.5ms)  
SELECT "fruits".* 
FROM "fruits" 
WHERE "fruits"."deleted_at" IS NULL AND "fruits"."type" IN ('Blueberry') AND "sites"."id" = $1 
ORDER BY "lft" LIMIT 1  [["id", 1]]
```

**Comment by Strnadj** [comment]
I am not happy to open this issue, but this fix breaks:

```
Superclass (i.e. Principal):
--SubClass1 (i.e. Group) <-- just groups are nested
--SubClass2 (i.e. User)
```

`Group.self_and_descendants....` fails with `undefined method 'nested_set_scope'` because

```
self.class.base_class.nested_set_scope # Principal is base_class
```

is not defined.
