### ISSUE TITLE
Order children nodes by column

### ISSUE THREAD

**Issue by ilyadoroshin** [collectiveidea/awesome_nested_set#240]
I've got structure like this:
- Fruits
  - Orange
  - Pear 
  - Apple
- Vegetables
  - Potato
  - Cucumber
  - Pumpkin

How can I order roots and it's children by name?
I guess, default scope for sorting is `:lft`, and it filled on child creation.
Is it possible to rebuild the tree with `default_scope :name`?

**Comment by morganchristiansson** [comment]
You can use `@item.children.except(:order).order("your_sort_column")` as suggested in http://stackoverflow.com/questions/1347885/awesome-nested-set-order-by/21582878#21582878
