### ISSUE TITLE
Fetch full tree and order children

### ISSUE THREAD

**Issue by Linuus** [collectiveidea/awesome_nested_set#271]
Hi

I have nested comments which can be added to articles. The comments are displayed with the newest comment at the top. 

```
- Comment 3
- Comment 2
- Comment 1
```

However, the replies to a comment is ordered with the oldest first. Like this:

```
- Comment 3
  - Comment 4
  - Comment 5
- Comment 2
  - Comment 6
    - Comment 8
    - Comment 9
  - Comment 7
- Comment 1
```

Can I fetch all comments somehow and order them like this by default?

I would rather not do the ordering in Ruby since I fetch more comments dynamically with a "Load more..." button (like Disqus) and sorting in Ruby will make this a bit harder...

**Comment by Linuus** [comment]
@parndt Any input here?

**Comment by parndt** [comment]
This sounds unlike a nested set.  You'd have to do something like this (basically re-implementing `roots`):

```ruby
Comment.unscoped.where(parent_id: nil).order("created_at DESC")
```

This would find you the top-level (root) nodes.  Then, when you iterate through the children, you'll have to make sure to do something like this:

```ruby
Comment.unscoped.where(parent_id: nil).order("created_at DESC").each do |comment|
  comment.children.order("created_at DESC")
end
```

Does this help?

**Comment by parndt** [comment]
I've tried to implement support for eager loading `descendants` into this library, but Rails doesn't like it because it relies on instances being loaded:

```ruby
has_many :descendants, -> (node) {
          order(quoted_order_column_name).
            where("#{quoted_left_column_name} > #{node.left}").
            where("#{quoted_right_column_name} < #{node.right}")
        }, class_name: self.base_class.to_s
```

**Comment by Linuus** [comment]
I do kind of what you suggest at the moment.

```ruby
<% discussion.comments.roots.each do |comment| %>
  <% if comment.leaf? %>
    <%= render partial: "comment", collection: [comment] %>
  <% else %>
    <%= render partial: "comment|, collection: comment.self_and_descendants %>
  <% end %>
<% end %>
```

But it may end up doing a lot of requests to the DB if there are many root nodes which have children. One to fetch all roots and then one for each root with children.

Eager loading would have been nice :) I'll experiment a bit with it.
