### ISSUE TITLE
after_create callbacks cannot see ancestors

### ISSUE THREAD

**Issue by theozaurus** [collectiveidea/awesome_nested_set#29]
I've got a simple subject hierarchy, one of my after_create callbacks needs to know the names of all of the ancestors so I can generate a neat name "foo/bar/baz". To do this I was using the self_and_ancestors method. However, on closer inspection this uses a named scope - so will only return values that are already saved in the database, and as each parents left and right columns are updated after the leaf has been saved - it only ever returns it's self.

Now I was thinking of altering the code to detect if it's a new record and fallback to a more recursive method of returning the ancestors but it occurs to me this will cause no end of pain for people who are using self_and_ancestors in a chain of named_scopes.

How would you deal with this?

**Comment by Jefferson-Faseler** [comment]
For anyone else that is encountering this issue, a solution my team found was to use [after_commit](https://apidock.com/rails/ActiveRecord/Transactions/ClassMethods/after_commit).
```
after_commit :some_hook, on: :create
```

This can still use conditions like `if` and `unless`.
