### ISSUE TITLE
children_count does not work

### ISSUE THREAD

**Issue by imshenitsky** [collectiveidea/awesome_nested_set#294]
Optional field "children_count" always 0. 
Actually I can use .children method but this is advanced hit to db.
I did simple as described:

``` ruby
root = Category.create!(:name => 'Root')
  ch = Category.create!(:name => 'First')
  ch.move_to_child_of(root)
root.reload
```

**Comment by parndt** [comment]
@imshenitsky ooh interesting, would you be willing to contribute a failing test so that we can fix the underlying issue please?

**Comment by laerciocrestani** [comment]
Put on Category Model
```acts_as_nested_set :counter_cache => :children_count```

**Comment by kaleemullah** [comment]
same problem for me even I've added acts_as_nested_set :counter_cache => :children_count

**Comment by parndt** [comment]
Would appreciate a failing test case for this if anyone has a chance?

**Comment by dgilperez** [comment]
Seeing the same here with Rails 4.2.3. 

I added the `children_count` column and I'm using the counter like this: 

````
acts_as_nested_set scope: [:commentable_id, :commentable_type], counter_cache: :children_count
````

Counter cache just does not update. 

You can have a look [here](https://github.com/dgilperez/participacion/blob/issue-143/app/models/comment.rb#L2) and a [failing test here](https://github.com/dgilperez/participacion/blob/issue-143/spec/features/comments_spec.rb#L89).

**Comment by graygilmore** [comment]
I couldn't get this working with `counter_cache: :children_count` but I was able to get it working with `counter_cache: true`.

**Comment by serghost** [comment]
Any news?
