### ISSUE TITLE
move_to_child_of does not update counter_cache

### ISSUE THREAD

**Issue by leifcr** [collectiveidea/awesome_nested_set#295]
Works when setting the parent and saving the model, but not when using move_to_child_of
Environment: Rails 4.2 Ruby 2.2

Model:

``` ruby
class Group < ActiveRecord::Base
  acts_as_nested_set counter_cache: :children_count
end
```

Migration

``` ruby
class CreateGroups < ActiveRecord::Migration
  def change
    create_table :groups do |t|
      t.string :title
      t.integer :parent_id, default: nil, index: true
      t.integer :lft, index: true
      t.integer :rgt, index: true
      t.integer :depth, index: true
      t.integer :children_count, default: 0

      t.timestamps
    end
  end
end
```

Code for testing move_to_child_of _(Result: children_count value: 0)_

``` ruby
r  = Group.create(title: "root")
g = Group.create(title: "group 1")
g.move_to_child_of(r)
g = Group.create(title: "group 2")
g.move_to_child_of(r)
g = Group.create(title: "group 3")
g.move_to_child_of(r)
r.reload
puts "Children count for root: #{r.children_count}"
# -> Children count for root: 0
```

Code for testing parent_id= _(Result:correct children_count value)_

``` ruby
r  = Group.create(title: "root")
g = Group.create(title: "group 1")
g.parent_id = r.id
g.save!
g = Group.create(title: "group 2")
g.parent_id = r.id
g.save!
g = Group.create(title: "group 3")
g.parent_id = r.id
g.save!
r.reload
puts "Children count for root: #{r.children_count}"
# -> Children count for root: 3
```

Code for testing parent= _(Result: double children_count value)_

``` ruby
r  = Group.create(title: "root")
g = Group.create(title: "group 1")
g.parent = r
g.save!
g = Group.create(title: "group 2")
g.parent = r
g.save!
g = Group.create(title: "group 3")
g.parent = r
g.save!
r.reload
puts "Children count for root: #{r.children_count}"
# -> Children count for root: 6 
```

**Comment by parreirat** [comment]
Was looking into this just now, my children_count column never had any values (no DB default set).

**Comment by parreirat** [comment]
Looking though the source code I found another valid way that currently works well with the :counter_cache column, creating and destroying the records directly on the has_many :children association created.

 In your case, it'd pan out to this:

r.children.create
r.children.destroy

Those would correctly modify the :counter_cache column.

**Comment by parreirat** [comment]
Forked my own repo, created the tests for the conditions under which the :counter_cache column should be updated.
Take a look if you don't mind, and tell me if you agree with the tests/what you'd modify :)

https://github.com/parreirat/awesome_nested_set/commit/a2de48f12beb8d1f96b130dc6e53d78cb53eca2b

**Comment by leifcr** [comment]
The tests looks good as far as I can see

**Comment by chip-miller** [comment]
Any progress on this?  It would be cool to have it working :)

**Comment by parreirat** [comment]
Sorry, have been very busy, had even forgot this. Will try to pick it up when I have some free time, no promises though!
