### ISSUE TITLE
deadlocks on non English PostgreSQL and SQLServer

### ISSUE THREAD

**Issue by marutosi** [collectiveidea/awesome_nested_set#298]
http://www.redmine.org/issues/19040

This line does not catch deadlocks.
https://github.com/collectiveidea/awesome_nested_set/blob/v2.1.5/lib/awesome_nested_set/awesome_nested_set.rb#L553

**Comment by parndt** [comment]
According to the issue linked you've stopped using this library.

Are you able to suggest an alternative line that would catch deadlocks? :smile:

**Comment by marutosi** [comment]
http://www.redmine.org/issues/6579#note-45

**Comment by parndt** [comment]
Can you suggest a change via a pull request mechanism please?

**Comment by marutosi** [comment]
No, thanks.
Redmine 3.0 stopped using this library and I am not interested.

**Comment by marutosi** [comment]
I don't know why you close this issue with nothing to fix?
Do you mean you won't fix?

**Comment by parndt** [comment]
I have no way of diagnosing as I don't have any of the databases listed, and as redmine no longer uses this library we can't check with the reporter of the issue on your end, either.

**Comment by marutosi** [comment]
Thank you.
Github has "wontfix" label.
I suggest you set "wontfix" label to this issue.

**Comment by parndt** [comment]
I'd like to fix it, but I don't have the means to.

**Comment by marutosi** [comment]
You can create new label per repository in following link and add label to issues if you have permissions of repository.
https://github.com/collectiveidea/awesome_nested_set/labels

**Comment by marutosi** [comment]
Rails has many labels.
https://github.com/rails/rails/labels
