### ISSUE TITLE
rebuild! set "lft" and "rgt" are 1 and 2 if :scope is defined

### ISSUE THREAD

**Issue by marutosi** [collectiveidea/awesome_nested_set#299]
http://www.redmine.org/issues/14335

On Redmine last revision [13839](http://www.redmine.org/projects/redmine/repository/revisions/13839) which uses awesome_nested_set gem with awesome_nested_set 3.0.2:

<pre>
$ echo 'select lft, rgt from issues;' | sqlite3 db/test.sqlite3
1|2
3|4
5|6
7|8
9|10
11|12
13|14
15|16
17|18
19|20
21|22
23|24
25|26
27|28
</pre>

<pre>
$ RAILS_ENV=development ruby bin/rails console
Loading development environment (Rails 4.1.8)
1.9.3-p551 :001 > Issue.update_all "lft = NULL, rgt = NULL"
  SQL (97.5ms)  UPDATE "issues" SET lft = NULL, rgt = NULL
 => 14 
1.9.3-p551 :002 > Issue.rebuild!(false)
.
.
.
</pre>

<pre>
$ echo 'select lft, rgt from issues;' | sqlite3 db/test.sqlite3
1|2
1|2
1|2
1|2
1|2
1|2
1|2
1|2
1|2
1|2
1|2
1|2
1|2
1|2
</pre>

With this change:

<pre>
diff --git a/app/models/issue.rb b/app/models/issue.rb
--- a/app/models/issue.rb
+++ b/app/models/issue.rb
@@ -41,7 +41,8 @@ class Issue < ActiveRecord::Base
   has_many :relations_from, :class_name => 'IssueRelation', :foreign_key => 'issue_from_id', :dependent => :delete_all
   has_many :relations_to, :class_name => 'IssueRelation', :foreign_key => 'issue_to_id', :dependent => :delete_all
 
-  acts_as_nested_set :scope => 'root_id', :dependent => :destroy
+  # acts_as_nested_set :scope => 'root_id', :dependent => :destroy
+  acts_as_nested_set :dependent => :destroy
   acts_as_attachable :after_add => :attachment_added, :after_remove => :attachment_removed
   acts_as_customizable
   acts_as_watchable
</pre>

<pre>
$ RAILS_ENV=development ruby bin/rails console
Loading development environment (Rails 4.1.8)
1.9.3-p551 :001 > Issue.update_all "lft = NULL, rgt = NULL"
  SQL (420.8ms)  UPDATE "issues" SET lft = NULL, rgt = NULL
 => 14 
1.9.3-p551 :002 > Issue.rebuild!(false)
.
.
.
</pre>

<pre>
$ echo 'select lft, rgt from issues;' | sqlite3 db/test.sqlite3
1|2
3|4
5|6
7|8
9|10
11|12
13|14
15|16
17|18
19|20
21|22
23|24
25|26
27|28
</pre>

P.S.
awesome_nested_set 3.0.2 breaks Redmine due to 87d8c7cc94eadf08 #292.
http://www.redmine.org/issues/14534#note-45

**Comment by parndt** [comment]
Seems like the code you changed is inside your own codebase?

**Comment by marutosi** [comment]
Yes, this line.
http://www.redmine.org/projects/redmine/repository/entry/tags/2.6.2/app/models/issue.rb#L47

**Comment by parndt** [comment]
@finbarr what do you think?

**Comment by chip-miller** [comment]
I had a similar issue... what solved it for me was ensuring that I only move/create children *in the same scope*.
