### ISSUE TITLE
Rebuild tree when removing a node

### ISSUE THREAD

**Issue by Linuus** [collectiveidea/awesome_nested_set#304]
Hi!

I use awesome_nested_set to create nested comments. If I remove a comment which is not a leaf, it deletes all descendants as well. Can aweseome_nested_set only destroy the node I select and connect the parent to the descendant instead?

```
Before:
Comment 1
   Answer 1   <--- Destroy
     Answer 2

After:
Comment 1
  Answer 2
```

Is that possible?

**Comment by PhilCoggins** [comment]
@Linuus [Defined behavior](https://github.com/collectiveidea/awesome_nested_set/blob/master/spec/models/users_spec.rb#L805) is to delete all leaves when deleting its parent.

Maybe in your application you could override the `delete` method in your nested set model and reassign  its leaves before calling `super`?
