### ISSUE TITLE
Destroy takes a very long time

### ISSUE THREAD

**Issue by Linuus** [collectiveidea/awesome_nested_set#305]
Hi!

I'm using this gem to provide nested comments in a discussion. I have this setting:

``` ruby
acts_as_nested_set scope: [:commentable_id, :commentable_type], dependent: :destroy
```

I tried to destroy a discussion which had 300 comments, and it takes a looong time. It runs `destroy` on each comment and also updates `lft` and `rgt`.

Can I make improve this somehow? I tried to use `dependent: :delete_all` but it seems to do exactly the same...

**Comment by reneedv** [comment]
I'm having the same problem. Any updates on this?

**Comment by jackcasey** [comment]
Us too.
