### ISSUE TITLE
lft and rgt are incorrect.

### ISSUE THREAD

**Issue by lemingos** [collectiveidea/awesome_nested_set#310]
At some point of using my app, Category lft and rgt values are incorrect. 
Did you expirence similar issues?
That is causing unexpected bahaviour like fetching incorrect ancestors etc. 
Any idea how can I debug it?

I've created this test:

```
should 'create categories with proper lft and rgt values' do
      10.times do
        FactoryGirl.create(:category)
        assert_equal Category.count * 2, Category.minimum(:lft) - 1 + Category.maximum(:rgt)
        Category.all[rand(Category.count)].destroy
        assert_equal Category.count * 2, Category.minimum(:lft) - 1 + Category.maximum(:rgt)
      end
    end
```

AFAIK it should not fail but it is. I wonder if acts_as_paranoid can be the cause ot if.

**Comment by mtomov** [comment]
Very likely it is `acts_as_paranoid`. Have a look at 
https://github.com/swanandp/acts_as_list/issues/158

for a similar trouble. Check the [default scope](https://github.com/collectiveidea/awesome_nested_set/blob/783b41533c4927c152175a5bb8504e80bffbb7e9/lib/awesome_nested_set/model.rb#L81)
