### ISSUE TITLE
Ability to set lft etc directly when loading seed data for tests

### ISSUE THREAD

**Issue by snoblenet** [collectiveidea/awesome_nested_set#315]
When I try to load seed data for tests, I get an error that looks like this:

```
ActiveRecord::ActiveRecordError: Unauthorized assignment to lft: it's an internal field handled by acts_as_nested_set code, use move_to_* methods instead.
```

Is there some way to temporarily override this protection while loading seed data? Thanks.

**Comment by lacco** [comment]
I guess it should be possible to set it using ```write_attribute(:lft, XX)```. I am using https://github.com/zdennis/activerecord-import for importing seed data, this gem can directly generate SQL to bypass this validation.

**Comment by cheenwe** [comment]
@snoblenet   remove it in  your controller:   :lft, :rgt, :depth, :children_count
it work for me~~

    def department_params
      params.require(:department).permit(:name, :parent_id)
    end

**Comment by droberts84** [comment]
You can force it with `update_columns`
