### ISSUE TITLE
What does the reload method do?

### ISSUE THREAD

**Issue by kgish** [collectiveidea/awesome_nested_set#318]
I would like to know what the `reload` method actually does

As described in the wiki example, must one call `reload` after every call to `move_to_child_of` ?

I've tried nested calls with and without `reload` and there doesn't seem to be any difference with the results.

Well actually, without it goes alot faster!

Maybe I am missing something.

**Comment by edjarris** [comment]
I have the same question. Before read the documentation in my seed.rb I create category data like this:

```
# seed.rb
running_category = Category.find_or_create_by!(name: "Running")
running_shoes = Category.find_or_create_by!(name: "Shoes", parent: running_category )
```

```
# Model Category.rb
class Category < ActiveRecord::Base
  acts_as_nested_set :counter_cache => :children_count
```

Everything seems to work fine, but after read the documentation I decided to move my seed like this:

```
# Seed.rb
running_category = Category.find_or_create_by!(name: "Running")
running_shoes = Category.find_or_create_by!(name: "Shoes")
running_shoes.move_to_child_of(running_category)
running_category.reload

```
I found that my root category (Running) the field children_count wasn't updated, I expected the method reload do the task to update this kind of data.

Maybe I amb doing/understanding somthing wrong.

**Comment by edjarris** [comment]
Looks like a pending merge fix that https://github.com/collectiveidea/awesome_nested_set/pull/323
