### ISSUE TITLE
undefined method connection for Instance

### ISSUE THREAD

**Issue by philister** [collectiveidea/awesome_nested_set#327]
I could not reproduce it. But my guess is: there is a deadlock and it  tries to catch it in

    bundle/ruby/2.2.0/gems/awesome_nested_set-3.0.3/lib/awesome_nested_set/model/transactable.rb:20:in `rescue in in_tenacious_transaction'
    bundle/ruby/2.2.0/gems/awesome_nested_set-3.0.3/lib/awesome_nested_set/model/transactable.rb:15:in `in_tenacious_transaction'
    bundle/ruby/2.2.0/gems/awesome_nested_set-3.0.3/lib/awesome_nested_set/model/movable.rb:103:in `block in move_to'

where the connection-method is called on an instance. Which is not possible since rails 4

**Comment by otavioschwanck** [comment]
i have same error.

**Comment by philister** [comment]
#330
