### ISSUE TITLE
awesome_nested_set tries to access record with id=1 even when it doesn't exist.

### ISSUE THREAD

**Issue by shelvacu** [collectiveidea/awesome_nested_set#334]
When trying to use awesome_nested_set on an empty table, it tries to access the very first record and fails.

```
rails (4.2.6)
activerecord (4.2.6)
awesome_nested_set (3.0.3)
```

Code to reproduce:

``` ruby
require 'active_record'
require 'awesome_nested_set'
require 'sqlite3'

ActiveRecord::Base.establish_connection(
  adapter: 'sqlite3',
  database: 'testans.db'
)

ActiveRecord::Base.connection.execute("CREATE TABLE IF NOT EXISTS 'nodes' (
id PRIMARY KEY,
name, 
parent_id, 
lft, 
rgt, 
depth)")

class Node < ActiveRecord::Base
  acts_as_nested_set
end

Node.create
```

**Comment by leifcr** [comment]
@shelvacu did you figure out this one? I have the same issue now.

**Comment by leifcr** [comment]
Found this to be an issue when using mariadb 10.4 docker image. Does not seem to be a problem with mysql 5.6 or 5.7 docker images.

**Comment by leifcr** [comment]
Folow-up on this issue. it is only an issue if you have an existing mysql docker-image and reuse the data_dir with a mariadb docker image. Please close this issue, as latest verison works fine.
