### ISSUE TITLE
touch failed when setting parent_id

### ISSUE THREAD

**Issue by hw676018683** [collectiveidea/awesome_nested_set#335]
``` ruby
class A < ActiveRecord::Base
  has_many :bs
end

class B < ActiveRecord::Base
  acts_as_nested_set

  belongs_to :a, touch: true
end
```

Problem:

this will touch a

``` ruby
B.create a_id: 1

```

this will not touch a

``` ruby
B.create a_id: 1, parent_id: 1

```

I look through the source code. I find rails will execute `model.changed?` before touching
if set parent_id, `model.changed?` is false. The it fails

Ruby 2.2.3 + Rails 4.2.6

**Comment by hw676018683** [comment]
```ruby
class B < ActiveRecord::Base
  belongs_to :a, touch: true

  acts_as_nested_set
end
```
Changing the order can fix it, but this may be opportunistic.

**Comment by lookitsatravis** [comment]
I'm running into this same issue on a project. Changing the statement order as @hw676018683 suggests does indeed fix it.
