### ISSUE TITLE
Non root nodes gets shown in views

### ISSUE THREAD

**Issue by kinsomicrote** [collectiveidea/awesome_nested_set#344]
I want to present all the root nodes in a drop-down, I have this line of code to do that
```
<%= f.select :parent_id, nested_set_options(Qeturah::Category.roots, @category) {|i| "#{'-' * i.level} #{i.name}" },
    { include_blank: true } %>
```
But it still lists all non root nodes.
When I run `Qeturah::Category.roots` in `rails c` it lists only root nodes. What could I be doing wrong?

**Comment by danielmorrison** [comment]
The `nested_set_options` helper is intended to get all the nodes. You can just do a basic select with the roots: `<%= f.select :parent_id, Qeturah::Category.roots.map { |p| [ p.name, p.id ] }, { include_blank: true } %>`
