### ISSUE TITLE
undefined local variable or method `acts_as_nested_set'

### ISSUE THREAD

**Issue by emi0918** [collectiveidea/awesome_nested_set#354]
I am currently using Rails 4.2.5 for my project. In my gemfile, the way I install is :
gem 'awesome_nested_set'

Even though I install successfully, the problem is happened in the production environment. 
Error: 
undefined local variable or method `acts_as_nested_set'

**Comment by danielmorrison** [comment]
Maybe it isn't getting required in the migration? I don't know why that would be offhand, but you could always `require "awesome_nested_set"` in the top of the file and see if that fixes it.

**Comment by emi0918** [comment]
# gem list
actioncable (5.0.0)
actionmailer (5.0.0, 4.2.5)
actionpack (5.0.0, 4.2.5)
actionview (5.0.0, 4.2.5)
activejob (5.0.0, 4.2.5)
activemodel (5.0.0, 4.2.5)
activerecord (5.0.0, 4.2.5)
activesupport (4.2.5)
airbrussh (1.1.0, 1.0.2)
arel (7.1.1, 6.0.3)
autoprefixer-rails (6.4.1, 6.3.6)
awesome_nested_set (3.1.1, 3.0.2)



I did require "awesome_nested_set", but it says
cannot load such file -- awesome_nested_set

**Comment by dominiceden** [comment]
@emi0918 I too had the same problem. I managed to fix it by changing my Gemfile to:

`gem 'awesome_nested_set', '~> 3.1'`

Then running `bundle update` and restarting my server.

This seems like a bit of an odd issue and I think I fixed it by luck more than anything else....

**Comment by nodox** [comment]
@dominiceden solution fixed my issue

**Comment by WuJoo** [comment]
I have a similar problem like @emi0918 but @dominiceden solution hasn't fixed the problem. Can anyone help me? I am using rails 5.2.
