### ISSUE TITLE
Is the readme the whole documentation?

### ISSUE THREAD

**Issue by bsylvain** [collectiveidea/awesome_nested_set#356]
It seems the documentation is missing a few important points : 

There is three kind of callbacks, for moving, adding and removing. There is no indication on how to move, add or remove. 

There is a link to examples, the domain is available for purchase.

I'd like to use awesome_nested_set, but it really need some docs.

**Comment by eddanger** [comment]
@bsylvain This has been helpful to me from the wiki: https://github.com/collectiveidea/awesome_nested_set/wiki/Awesome-nested-set-cheat-sheet
