### ISSUE TITLE
`order_column` breaks `nested_set_options`

### ISSUE THREAD

**Issue by sambostock** [collectiveidea/awesome_nested_set#361]
Using `order_column` breaks the `nested_set_options` helper.

The [helper](https://github.com/collectiveidea/awesome_nested_set/blob/76bfb779ef882984f578238c1e5bdb76ee2b29fd/lib/awesome_nested_set/helper.rb#L24) makes use of `self_and_descendants`, which sorts by the `order_column`.

This can lead to a completely wrong hierarchy being rendered. For example, if the order_column was `:name`, and the following structure existed:

```
A
D
- C
B
- E
```

Using the following code from the `nested_set_options` example:

```ruby
nested_set_options(named_items) {|i| "#{'-' * i.level} #{i.name}" }
```
would render the following hierarchy:

```
A
B
- E
- C
D
```

This is because the results of `self_and_descendants` is ordered by `order_column`, which leads to the final ordering:

```ruby
named_items.roots
# => [A, B, D]
named_items.roots.map(&:self_and_descendants)
# => [[A],[B, E],[C, D]]
named_items.roots.flat_map(&:self_and_descendants)
# => [A, B, E, C, D]
```

It seems logical that when rendering a hierarchical structure, the ordering should only be applied across children:

```
A
B
- E
D
- C
```

**Comment by matpowel** [comment]
This was the nail in the coffin for us using this gem, it's a decent gem but this was non-trivial to workaround and the Ancestry gem seems superior
