### ISSUE TITLE
roots query is not ordered by lft

### ISSUE THREAD

**Issue by nruth** [collectiveidea/awesome_nested_set#362]
I was under the impression `lft` was a default used to order queries, but debugging a test failure I found that calls like `x.foos.roots` are sent to postgres without an order statement and come back in random order.

```
SELECT "foos".* FROM "foos" WHERE "foos"."foo_id" = $1 AND "foos"."parent_id" IS NULL
```

The data does have lft in the expected order, just the query surprisingly doesn't use it.

**Comment by danielmorrison** [comment]
Yeah that needs to change. I'd welcome a PR if you can get to it before I do.
