### ISSUE TITLE
Is there an easy way to change the order of elements (left or right) in the same parent?

### ISSUE THREAD

**Issue by jmuheim** [collectiveidea/awesome_nested_set#365]
Is there an easy way to change the order of elements (left or right) in the same parent?

I'm missing something like `category.move_left` (for only one step) or `category.move_left_most`.

Also it would be good to be able to move to a specific position by providing the target element's ID.

**Comment by HermannHH** [comment]
@jmuheim I also needed this. Couldn't find it in the docs or cheat sheet. But this gem does provide this functionality. To change the order of children of the same parent you could use the `move_to_right_of` and `move_to_left_of` methods. 

So for example. Let's say B and C are both children of A. If you want to move C to appear before B then you can do `C.move_to_left_of(B.id)` or `B.move_to_right_of(C.id)`.

As you can see, if you know the details of the target and source elements, you can move them around as your heart desires.
