### ISSUE TITLE
Move "Awesome nested set cheat sheet" into README.md

### ISSUE THREAD

**Issue by 1c7** [collectiveidea/awesome_nested_set#367]
Hi, Thanks for writing this gem.

Instance method document is really important.
I think we should move this 
https://github.com/collectiveidea/awesome_nested_set/wiki/Awesome-nested-set-cheat-sheet

into README

What you guys think?

**Comment by ethagnawl** [comment]
This is a great idea, @1c7! Even a link to the wiki page would be an improvement.
