### ISSUE TITLE
counting childrens and their childrens

### ISSUE THREAD

**Issue by krtschmr** [collectiveidea/awesome_nested_set#369]
comment = object.comment.create
    # comment.comments_count = 1
    children = comment.childrens.create
    #comment.childrens_count = 1
    children.childrens.create
    # children.childrens_count = 1

this is somehow expected behaviour, but, shouldn't it be more like

    object.comments_count = 3 # in total 3 comments to this mods have been written
    comment.childrens_count = 2 # in total there are 2 childrens to this comment

should we make this configurable? something like `cound_child_children=true` or is our expected behavior away from reality?

**Comment by cars10** [comment]
You can use `comment.descendants.count`. `children` are only the *direct* children.

**Comment by Mziserman** [comment]
I use this method which does not depend on rgt/lft
```ruby
  def calculate_descendant_count
    result = self.class.connection.exec_query(
      ActiveRecord::Base.send(:sanitize_sql_array,
                              [
                                "WITH RECURSIVE search_tree(id, id_path) AS (
                                  SELECT id, ARRAY[id]
                                  FROM #{self.class.table_name}
                                  WHERE parent_id = ?
                                UNION ALL
                                  SELECT #{self.class.table_name}.id, id_path || #{self.class.table_name}.id
                                  FROM search_tree
                                  JOIN #{self.class.table_name} ON #{self.class.table_name}.parent_id = search_tree.id
                                  WHERE NOT #{self.class.table_name}.id = ANY(id_path)
                                )
                                SELECT COUNT(*) FROM search_tree", id
                              ])
    )

    result.rows[0][0].to_i
  end
```
else you can just
```ruby
(node.rgt - node.lft - 1) / 2
```
