### ISSUE TITLE
Rails 5.1.0 support

### ISSUE THREAD

**Issue by thezed** [collectiveidea/awesome_nested_set#373]
Need Rails 5.1.0 support

**Comment by Rikko999** [comment]
+

**Comment by clairity** [comment]
awesome_nested_set is now the only gem (via the acts_as_commentable_with_threading gem) that's preventing my upgrade to rails 5.1.0. would really appreciate an update! 😊

**Comment by joshRpowell** [comment]
@clairity the update was applied here #372

**Comment by thezed** [comment]
Nice 👍🏻
