### ISSUE TITLE
Feature: self_and_children

### ISSUE THREAD

**Issue by map7** [collectiveidea/awesome_nested_set#376]
I've got a need to list the parent and it's children and was thinking that there should be a self_and_children feature.

**Comment by toastercup** [comment]
@map7 This feature exists as `self_and_descendants`, which will return a flat collection of the parent and all of its nested children. You can find the method in question here: https://github.com/collectiveidea/awesome_nested_set/blob/76bfb779ef882984f578238c1e5bdb76ee2b29fd/lib/awesome_nested_set/model/relatable.rb#L47-L51
