### ISSUE TITLE
basic descendants is broken?

### ISSUE THREAD

**Issue by vectorz** [collectiveidea/awesome_nested_set#38]
>> ag.children

=> []

>> ag2 = AccountGroup.create({:name => 'System Administrators'})

=> #<AccountGroup id: 173, name: "System Administrators", description: nil, parent_id: nil, lft: 345, rgt: 346, slfgrp: nil, created_at: "2010-02-26 08:56:16", updated_at: "2010-02-26 08:56:16">

>> ag3 = AccountGroup.create({:name => 'Architecture'})

=> #<AccountGroup id: 174, name: "Architecture", description: nil, parent_id: nil, lft: 347, rgt: 348, slfgrp: nil, created_at: "2010-02-26 08:56:23", updated_at: "2010-02-26 08:56:23">

>> ag2.move_to_child_of ag

=> []

>> ag3.move_to_child_of ag

=> []

>> ag.children

=> [#<AccountGroup id: 174, name: "Architecture", description: nil, parent_id: 172, lft: 344, rgt: 345, slfgrp: nil, created_at: "2010-02-26 08:56:23", updated_at: "2010-02-26 08:56:23">, #<AccountGroup id: 173, name: "System Administrators", description: nil, parent_id: 172, lft: 346, rgt: 347, slfgrp: nil, created_at: "2010-02-26 08:56:16", updated_at: "2010-02-26 08:56:16">]

>> ag.children.size

=> 2

>> ag4 = AccountGroup.create({:name => 'Platform Services'})

=> #<AccountGroup id: 175, name: "Platform Services", description: nil, parent_id: nil, lft: 349, rgt: 350, slfgrp: nil, created_at: "2010-02-26 08:58:03", updated_at: "2010-02-26 08:58:03">

>> ag4.move_to_child_of ag2

=> []

>> ag.children.size

=> 2

>> ag.descendants.size

=> 2

*\* Shouldn't descendants be equal to 3?  FTR, when I uninstall awesome_nested_set and install better_nested_set, without changing any of the above records in the DB, 'ag.all_children' returns 3.  'all_children' is the same method as 'descendants' , which I'm sure you already know.

**Comment by mibamur** [comment]
Why still open?
