### ISSUE TITLE
Deprecation warning when using Rails 5.2

### ISSUE THREAD

**Issue by brendanshean** [collectiveidea/awesome_nested_set#380]
I've started using Rails (5.2.0.alpha) and I've been getting the following:

DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "\"ed_nodes\".\"lft\"". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). (called from nested_set_scope at .rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/awesome_nested_set-3.1.3/lib/awesome_nested_set/model.rb:84)

**Comment by parndt** [comment]
Thanks for letting us know!

**Comment by brendanshean** [comment]
Any chance you can bump the release version to 3.1.4?

**Comment by parndt** [comment]
Yep - 3.1.4 released 👍

**Comment by brendanshean** [comment]
Thanks so much for the truly awesome gem, @parndt
