### ISSUE TITLE
Getting Left and right node with continuous order

### ISSUE THREAD

**Issue by anson2590** [collectiveidea/awesome_nested_set#385]
I am using rails 5.1 and when I try to run rspec I am facing issue like when I try to create Parent record: lft node is 3 and rgt node is 4. and in Child record: lft node is 4 and rgt node is 5. so "is_or_is_descendant_of?" method is failing. can you please tell, what is the issue.

**Comment by parndt** [comment]
Can you please provide example code which allows us to reproduce the error, as well as the full error stack trace?

**Comment by anson2590** [comment]
Thank You @parndt , It got fixed it was the issue with my code.
