### ISSUE TITLE
Unknown key: :order with Rails 6

### ISSUE THREAD

**Issue by jtapia** [collectiveidea/awesome_nested_set#406]
I'm getting this error using Rails 6 `ArgumentError (Unknown key: :order. Valid keys are: :class_name, :anonymous_class, :foreign_key, :validate, :autosave, :table_name, :before_add, :after_add, :before_remove, :after_remove, :extend, :primary_key, :dependent, :as, :through, :source, :source_type, :inverse_of, :counter_cache, :join_table, :foreign_type, :index_errors)`

I think that removing the `order` solved the issue https://github.com/collectiveidea/awesome_nested_set/blob/v3.0.1/lib/awesome_nested_set/awesome_nested_set.rb#L90

**Comment by parndt** [comment]
@jtapia thanks - so the guides say that we can use that https://edgeguides.rubyonrails.org/association_basics.html#scopes-for-has-many-order so I'm confused about why this would error.. is it somehow getting added to [has_many_children_options](https://github.com/collectiveidea/awesome_nested_set/blob/v3.0.1/lib/awesome_nested_set/awesome_nested_set.rb#L76)?

**Comment by ccastillop** [comment]
I think you have to use master https://github.com/collectiveidea/awesome_nested_set/pull/401 untill this PR is merged.
It works for me :)

**Comment by parndt** [comment]
This has been fixed
