### ISSUE TITLE
Children method demands argument???

### ISSUE THREAD

**Issue by a-ta-ta** [collectiveidea/awesome_nested_set#412]
(byebug) comment.children
*** ArgumentError Exception: wrong number of arguments (given 0, expected 1)

EXPECTED??? o_O

**Comment by ccastillop** [comment]
It's also happened to me: Rails 6.0.1 and awesome_nested_set (3.1.4)

I 've just upgraded to awesome_nested_set (3.2.0) and the bug dissapears 👍

**Comment by dnamsons** [comment]
This also occurs when updating from Rails 5.2.3 to 5.2.4
