### ISSUE TITLE
Scoping rebuild to 'current_user'

### ISSUE THREAD

**Issue by chrisedington** [collectiveidea/awesome_nested_set#435]
Hi,

I'm using the gem on a multi-tenanted application, allowing customers to design a "menu structure" from a Pages model.

There are over 100k menu items in the database, and when I run a rebuild upon "first run", it's looking like it's going to take 24 hours to complete.

I was hoping I could rebuild for a single tenant at a time, such as:

`current_user.pages.rebuild! `

The above still seems to rebuild every single item in the Page model (100k).

I haven't quite figured out whether I might need to run rebuild! again in production (likely), but if I do, 24 hours isn't going to work.

Can anyone offer any advice on how I can better implement this use case?

**Comment by OpakAlex** [comment]
Amazing solution to close issues ;))))

**Comment by stefanoverna** [comment]
Any news on this one? We're facing exactly the same situation.

Given that a `:scope option` is available, which suggests that you can have several distinct lists within the same table, the ability to reconstruct the tree at each scope level would be quite logical.

Any suggestions for achieving this effect even in userland would be greatly appreciated.. thank you very much!

**Comment by OpakAlex** [comment]
I also have issue with this. +1

**Comment by fydelio** [comment]
Hey, I have this issue too. +1. Can we reopen.
