### ISSUE TITLE
Publish Rails 7 compatible gem

### ISSUE THREAD

**Issue by andrewhampton** [collectiveidea/awesome_nested_set#462]
Now that https://github.com/collectiveidea/awesome_nested_set/pull/460 is merged, do you mind publishing v3.2.0 with rails 7 support to rubygems?

**Comment by peterberkenbosch** [comment]
Hello @parndt, can I help with this? Let me know.. Thanks <3

**Comment by parndt** [comment]
Thanks, released to rubygems 😄

**Comment by peterberkenbosch** [comment]
You are the best @parndt!
