### ISSUE TITLE
undefined method `arity' for an instance of Hash

### ISSUE THREAD

**Issue by jetienne** [collectiveidea/awesome_nested_set#489]
I found this error while upgrading to Rails 8:

```
undefined method `arity' for an instance of Hash
```
when loading

```
acts_as_nested_set
```

I'm not sure it's related to the last [commits](https://github.com/collectiveidea/awesome_nested_set/pull/487) that have been pushed. Should I wait or what should I do?

**Comment by danielmorrison** [comment]
@jetienne version 3.8.0 was just released. Try that and let us know if you still have issues.

**Comment by jetienne** [comment]
@danielmorrison Perfect, works like a charm. Thank you!
