### ISSUE TITLE
undefined local variable or method `acts_as_nested_set'

### ISSUE THREAD

**Issue by daihua** [collectiveidea/awesome_nested_set#56]
I am currently using rails 3 for my project. In my gemfile, the way I install is :
gem 'awesome_nested_set', '1.4.3' 

Even though I install successfully, the problem is happened in the migration process. 
Error: 
undefined local variable or method `acts_as_nested_set'

If I change the other to install, like that:
gem 'awesome_nested_set', :git => 'http://github.com/galetahub/awesome_nested_set.git'

In the installation, I have some warning but I do the migration is fine. However, in my server, I cannot install like my second way. I need to use the first way to install for my project, how can I solve the problem? 

Thanks.

**Comment by emi0918** [comment]
I am currently using Rails 4.2.5 for my project. In my gemfile, the way I install is :
gem 'awesome_nested_set'

Even though I install successfully, the problem is happened in the migration process. 
Error: 
undefined local variable or method `acts_as_nested_set'
