### ISSUE TITLE
rebuild! for parts of the tree

### ISSUE THREAD

**Issue by clemens** [collectiveidea/awesome_nested_set#79]
Hey guys,

it would be great if you could support passing options to rebuild! as in galetahub's fork: https://github.com/galetahub/awesome_nested_set/blob/master/lib/awesome_nested_set/base.rb#L183. This is really useful if you have big scopes trees and you are certain that parts of the tree are valid and you just need to update the tree for one scope.

My use case: I'm loading a category tree from a CSV file and each merchant has their own category tree. When Importing, I can't know the lft, rgt and level because I'm loading the CSV file directly, so I have to call rebuild! afterwards. But I do know is that the import of one merchant's category tree doesn't affect any other merchants' category trees. Walking the whole category has become a performance nightmare because I have lots of merchants with big category trees.

Could you implement that or should I submit a patch? I'm more than happy to do that ...

**Comment by kronn** [comment]
I just had the need to rebuild parts of the tree. In the end it was quicker to just rebuild and resort the entire tree. I would however be very interested in a solution to partial tree rebuilding to recover from similar data-issues.

@parndt, @clemens, @buffym does either one of you have any more starting points than the aforementioned fork?

(also, fancy meeting you here again, @clemens :smile:)
